{{ if .Values.webhook.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "spark-operator.fullname" . }}-webhook-init
  labels:
    {{- include "spark-operator.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ include "spark-operator.fullname" . }}-webhook-init
      {{- if .Values.istio.enabled }}
      annotations:
        "sidecar.istio.io/inject": "false"
      {{- end }}
    spec:
      serviceAccountName: {{ include "spark-operator.serviceAccountName" . }}
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: main
        image: {{ include "common.images.image" (dict "context" $ "repository" .Values.platformConfig.imageRepositoryRelease "imageRoot" .Values.image) | quote }}
        imagePullPolicy: {{ default "Always" .Values.platformConfig.imagePullPolicy | quote }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        command: ["/usr/bin/gencerts.sh", "-n", "{{ .Release.Namespace }}", "-s", "{{ include "spark-operator.fullname" . }}-webhook", "-p"]
{{ end }}
