apiVersion: v2
name: spark-operator
description: A Helm chart for Spark on Kubernetes operator
version: 1.0.2
appVersion: v1beta2-1.2.0-3.0.0
keywords:
  - spark
home: https://github.com/caicloud/spark-on-k8s-operator
maintainers:
  - name: kz33
